version: '3.8'
services:
  mongo:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: franquicias

  springboot:
    build: .
    container_name: franquicias
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/franquicias
    depends_on:
      - mongo

volumes:
  mongo_data: